version: '3'

services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: python spoilerchan/spoilerchan.py
        volumes:
            - .:/code
        env_file: .env
        depends_on:
            - db